stages:
  featurize:
    cmd: python ./src/data_preparation.py
    deps:
    - data
    - ./src/config.py
    - ./src/data_preparation.py
    outs:
    - ./model/feature/bottleneck_features_train.npy
    - ./model/feature/bottleneck_features_validation.npy
    - ./model/feature/bottleneck_features_test.npy
  train:
    cmd: python ./src/train.py
    deps:
    - ./model/feature/bottleneck_features_train.npy
    - ./model/feature/bottleneck_features_validation.npy
    - ./src/config.py
    - ./src/train.py
    outs:
    - ./log/metrics.csv
    - ./model/model.h5
    - ./model/model.json
  evaluate:
    cmd: python ./src/evaluate.py
    deps:
    - ./model/feature/bottleneck_features_test.npy
    - ./model/model.h5
    - ./model/model.json
    - ./src/config.py
    - ./src/evaluate.py
    metrics:
    - evaluation.json:
        cache: false
